inputs:
  arm_version:
    default: 11.3.rel1
    type: string

runs:
  using: composite
  steps:
  - name:
    shell: bash
    run: |
      echo 
      wget -q https://developer.arm.com/-/media/Files/downloads/gnu/${{inputs.arm_version}}/binrel/arm-gnu-toolchain-${{inputs.arm_version}-x86_64-arm-none-eabi.tar.xz
      tar -xf ${{arm_version}}.tar.xz
      echo "${{github.workspace}}/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH