inputs:
  flag_ninja:
    default: false
    type: boolean
  cmake_version:
    type: string
    
runs:
  using: composite
  steps:
  - run: sudo apt-get update
  - name: install ${{inputs.cmake_version}}
    shell: bash
    working-directory: ./scripts
    run: |
      ls
      echo $PWD
      echo ${{github.workspace}}
      echo ${{github.action_path}}
      bash ./install_dependencies.sh ${{inputs.flag_ninja}} ${{inputs.cmake_version}}

    