inputs:
  flag_ninja:
    default: false
    type: boolean
  cmake_version:
    type: string
    
runs:
  using: composite
  steps:
  - name: install ${{inputs.cmake_version}}
    shell: bash
    run: |
      ls
      echo $PWD
      echo ${{GITHUB_WORKSPACE}}
      bash ${{GITHUB_WORKSPACE}}/scripts/install_dependencies.sh ${{inputs.flag_ninja}} ${{inputs.cmake_version}}

    