inputs:
  flag_arm:
    default: false
    type: boolean

runs:
  using: composite
  steps:
  - if: ${{inputs.flag_arm}}
    shell: bash
    working-directory: ./action_scripts
    run: bash ./check_installs.sh