inputs:
  arm_path:
    default: https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
    type: string
  arm_tar_path:
    default: arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
    type: string
  arm_dir_path:
    default: ${{github.workspace}}/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi/bin
    type: string
  flag_arm:
    default: false
    type: boolean
  

runs:
  using: composite
  steps: 
  - if: ${{inputs.flag_arm}}
    name: execute script
    shell: bash
    run: bash ./install_pipeline_specific.sh ${{inputs.arm_path}} ${{inputs.arm_tar_path}} ${{inputs.arm_dir_path}}
