name: build test

on:
  workflow_call:
    inputs:
      name:
        type: string
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
  
jobs:
  build:
    name: build test
    runs-on: ${{ (inputs.buildSystem)}}
    steps:
    - name: echo variables
      run: |
        echo ${{inputs.name}}
        echo ${{inputs.buildSystem}}
        echo ${{inputs.workingBranch}}
    - name: evaluate inputs
      if: ${{inputs.name}} == test1
      run: echo if works!!!!!!!!!!!!!!!!!!!!!
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Uses checkout submodules
      uses: ./.github/actions/action_checkout_submodul
    - name: Checkout actions repo
      uses: actions/checkout@v3
      with: 
        repository: FloMertens/StateOS-BA/.github/actions/action_install_dependencies
        path: .github
        ref: ${{ inputs.workingBranch }}
        
    - name: install dependencies
      uses: ./.github/action_install_dependencies
    - name: install arm-none-eabi-gcc
      uses: ./.github/actions/action_install_arm-none-eabi-gcc
    - name: check arm-none-eabi-gcc version
      uses: ./.github/actions/action_check_installs
    - name: make test
      uses: ./.github/actions/action_make_test
    