name: build test

on:
  workflow_call:
    inputs:
      name:
        type: string
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
  
jobs:
  build:
    name: build test
    runs-on: ${{ (inputs.buildSystem)}}
    steps:
    - name: evaluate inputs
      if: ${{inputs.name}} == test1
      run: echo if works!!!!!!!!!!!!!!!!!!!!!

    - name: checkout repository
      uses: actions/checkout@v4
    - name: Uses checkout submodules
      uses: ./.github/actions/action_checkout_submodul

    - name: Checkout actions repo
      uses: actions/checkout@v3
      with: 
        repository: MertensFlo/StateOS_BA
        path: ref_actions_repo
        ref: ${{ inputs.workingBranch }}
        sparse-checkout: |
          .github/actions
    - name:
      run: |
        cd ref_actions_repo
        ls
    - name: install dependencies
      uses: ./ref_actions_repo/action_install_dependencies
    - name: install arm-none-eabi-gcc
      uses: ./.github/actions/action_install_arm-none-eabi-gcc
      with:
        arm_version: 11.3.rel1
    - name: check arm-none-eabi-gcc version
      uses: ./.github/actions/action_check_installs
    - name: make test
      uses: ./.github/actions/action_make_test
    