name: build test

on:
  workflow_call:
    inputs:
      name:
        type: string
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
      workingRepo:
        default: StateOS_BA
        type: string
      workingOrg:
        default: MertensFlo
        type: string
      arm_version:
        default: 11.3.rel1
        type: string
  
jobs:
  build:
    name: build test
    runs-on: ${{ (inputs.buildSystem)}}
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with: 
        submodules: 'true'
    #- name: Uses checkout submodules
    #  uses: ./.github/actions/action_checkout_submodul
    - name: Checkout actions repo for wanted branch
      uses: actions/checkout@v4
      with: 
        repository: ${{inputs.workingOrg}}/${{inputs.workingRepo}}
        path: ref_actions_repo
        ref: ${{ inputs.workingBranch }}
        sparse-checkout: |
          .github/actions
        sparse-checkout-cone-mode: false
    - name: install dependencies
      uses: ./ref_actions_repo/.github/actions/action_install_dependencies
    - name: install arm-none-eabi-gcc
      if: ${{inputs.name}} == StateOS
      uses: ./ref_actions_repo/.github/actions/action_install_arm-none-eabi-gcc
      with:
        arm_version: ${{ inputs.arm_version}}
    - name: check arm-none-eabi-gcc version
      uses: ./ref_actions_repo/.github/actions/action_check_installs
    - name: make test
      uses: ./ref_actions_repo/.github/actions/action_make_build
    