name: build test

on:
  workflow_call:
    inputs:
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
      workingRepo:
        default: StateOS_BA
        type: string
      workingOrg:
        default: MertensFlo
        type: string
      callerBranch:
        default: Testing_workflows
        type: string
      callerRepo:
        default: StateOS_BA
        type: string
      callerOrg:
        default: MertensFlo
        type: string
      arm_path:
        default: https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
        type: string
      arm_tar_path:
        default: arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
        type: string
      arm_dir_path:
        default: ${{github.workspace}}/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi/bin
        type: string
      cmake_version:
        default: cmake
        type: string
      flag_arm:
        default: false
        type: boolean
      flag_submodule:
        default: false
        type: boolean
      flag_ninja:
        default: false
        type: boolean
      flag_cmake_build:
        default: false
        type: boolean

  
jobs:
  build:
    name: build test
    runs-on: ${{ (inputs.buildSystem)}}
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{inputs.callerOrg}}/${{inputs.callerRepo}}
        ref: ${{ inputs.callerBranch }}
        submodules: ${{inputs.flag_submodule}}

    - name: install dependencies
      uses: ./.github/actions/universal/action_install_dependencies
      with: 
        flag_ninja: ${{inputs.flag_ninja}}
        cmake_version: ${{inputs.cmake_version}}

    