name: build test

on:
    workflow_call:
  
jobs:
    build:
      name: build test
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Uses checkout submodules
        uses: MertensFlo/StateOS_BA/.github/actions/action_checkout_submodul@Testing_workflows
      - name: install dependencies
        uses: MertensFlo/StateOS_BA/.github/actions/action_install_dependencies@Testing_workflows
      - name: install arm-none-eabi-gcc
        uses: ./.github/actions/action_install_arm-none-eabi-gcc
      - name: check arm-none-eabi-gcc version
        uses: ./.github/actions/action_check_installs
      - name: make test
        run: |
          cmake -S. -Bbuild -GNinja
          cmake --build build -v