name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-pipeline:
    uses: MertensFlo/StateOS_BA/.github/workflows/pipeline.yml@Testing_workflows
    with:
      buildSystem: ubuntu-latest
      workingBranch: Testing_workflows
      workingRepo: StateOS_BA
      workingOrg: MertensFlo
      callerBranch: Testing_workflows
      callerRepo: StateOS_BA
      callerOrg: MertensFlo
      arm_path: -q https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
      arm_tar_path: arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
      arm_dir_path: ${{github.workspace}}/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi/bin
      arm_condition: -qS
      cmake_version: cmake
      flag_arm: false
      flag_submodule: true
      flag_ninja: true
      example_test: true
      static_test: true
      unit_test: true
      