name: CI

on:
 # push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-pipeline:
    uses: MertensFlo/StateOS_BA/.github/workflows/pipeline.yml@Testing_workflows
    with:
      buildSystem: ubuntu-latest
      workingBranch: Testing_workflows
      workingRepo: StateOS_BA
      workingOrg: MertensFlo
      callerBranch: Testing_workflows
      callerRepo: StateOS_BA
      callerOrg: MertensFlo
      arm_version: 11.3.rel1
      cmake_version: cmake
      flag_arm: true
      flag_submodule: true
      flag_ninja: true
      example_test: true
      static_test: true
      unit_test: true
      