name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-pipeline:
    uses: MertensFlo/StateOS_BA/.github/workflows/pipeline.yml@Testing_workflows
    with:
      buildSystem: ubuntu-latest
      workingBranch: Testing_workflows
      workingRepo: StateOS_BA
      workingOrg: MertensFlo
      example_test: true
      static_test: true
      unit_test: true
      