name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-build:
    uses: MertensFlo/StateOS_BA/.github/workflows/pipeline.yml@Testing_workflows
    with:
      name: test1
      buildSystem: ubuntu-latest
      workingBranch: Testing_workflows