name: CI

on:
  workflow_call:
    inputs:
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
      workingRepo:
        default: StateOS_BA
        type: string
      workingOrg:
        default: MertensFlo
        type: string
      callerRepo:
        default: StateOS_BA
        type: string
      callerOrg:
        default: MertensFlo
        type: string
      arm_version:
        default: 11.3.rel1
        type: string
      flag_arm:
        default: false
        type: boolean
      flag_submodule:
        default: false
        type: boolean
      flag_ninja:
        default: false
        type: boolean
      example_test:
        default: false
        type: boolean
      static_test:
        default: false
        type: boolean
      unit_test:
        default: false
        type: boolean
  
jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      workingRepo: ${{inputs.workingRepo}}
      workingOrg: ${{inputs.workingOrg}}
      callerRepo: ${{inputs.callerRepo}}
      callerOrg: ${{inputs.callerOrg}}
      arm_version: ${{inputs.arm_version}}
      flag_arm: ${{inputs.flag_arm}}
      flag_submodule: ${{inputs.flag_submodule}}
      flag_ninja: ${{inputs.flag_ninja}}

  call-example:
    needs: call-build
    if: ${{inputs.example_test}}
    uses: ./.github/workflows/test.yml
    with:
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      workingRepo: ${{inputs.workingRepo}}
      workingOrg: ${{inputs.workingOrg}}
      callerRepo: ${{inputs.callerRepo}}
      callerOrg: ${{inputs.callerOrg}}
      arm_version: ${{inputs.arm_version}}
      flag_arm: ${{inputs.flag_arm}}
      flag_submodule: ${{inputs.flag_submodule}}
      flag_ninja: ${{inputs.flag_ninja}}
      current_test_element: example

  call-static-code-test:
    needs: call-build
    if: ${{inputs.static_test}}
    uses: ./.github/workflows/test.yml
    with:
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      workingRepo: ${{inputs.workingRepo}}
      workingOrg: ${{inputs.workingOrg}}
      callerRepo: ${{inputs.callerRepo}}
      callerOrg: ${{inputs.callerOrg}}
      arm_version: ${{inputs.arm_version}}
      flag_arm: ${{inputs.flag_arm}}
      flag_submodule: ${{inputs.flag_submodule}}
      flag_ninja: ${{inputs.flag_ninja}}
      current_test_element: static

  call-unit-test:
    needs: call-build
    if: ${{inputs.unit_test}}
    uses: ./.github/workflows/test.yml
    with:
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      workingRepo: ${{inputs.workingRepo}}
      workingOrg: ${{inputs.workingOrg}}
      callerRepo: ${{inputs.callerRepo}}
      callerOrg: ${{inputs.callerOrg}}
      arm_version: ${{inputs.arm_version}}
      flag_arm: ${{inputs.flag_arm}}
      flag_submodule: ${{inputs.flag_submodule}}
      flag_ninja: ${{inputs.flag_ninja}}
      current_test_element: unit