name: CI

on:
  workflow_call:
    inputs:
      name:
        type: string
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
      workingRepo:
        type: string
      workingOrg:
        type: string
      example_test:
        default: false
        type: boolean
      static_test:
        default: false
        type: boolean
      unit_test:
        default: false
        type: boolean
  
jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      name: ${{inputs.name}}
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      workingRepo: ${{inputs.workingRepo}}
      workingOrg: ${{inputs.workingOrg}}

  call-example:
    needs: call-build
    if: ${{inputs.example_test}}
    uses: ./.github/workflows/test.yml
    with:
      name: ${{inputs.name}}
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      current_test_element: example

  call-static-code-test:
    needs: call-build
    if: ${{inputs.static_test}}
    uses: ./.github/workflows/test.yml
    with:
      name: ${{inputs.name}}
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      current_test_element: static

  call-unit-test:
    needs: call-build
    if: ${{inputs.unit_test}}
    uses: ./.github/workflows/test.yml
    with:
      name: ${{inputs.name}}
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}
      current_test_element: unit