name: CI

on:
  workflow_call:
    inputs:
      name:
        type: string
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
  
jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      name: ${{inputs.name}}
      buildSystem: ${{inputs.buildSystem}}
      workingBranch: ${{inputs.workingBranch}}

#  call-example:
#     uses: ./.github/workflows/test.yml
#
#  call-static-code-test:
#    uses: ./.github/workflows/static_code_test.yml
#
# call-unit-test:
#    uses: ./.github/workflows/unit_test.yml