name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-build:
    uses: MertensFlo/StateOS_BA/.github/workflows/build_test.yml@Testing_workflows
    with:
      name: test1
      buildSystem: ubuntu-latest
      branch: ${{ env.GITHUB_REF#refs/heads/ }}

#  call-example:
#     uses: ./.github/workflows/test_test.yml
#
#  call-static-code-test:
#    uses: ./.github/workflows/static_code_test.yml
#
# call-unit-test:
#    uses: ./.github/workflows/unit_test.yml
