name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-workflow:
    uses: MertensFlo/StateOS_BA/.github/workflows/build_test.yml@1
  