name: install_arm-none-eabi-gcc

on:
  workflow_call:
    inputs:
      buildSystem:
        default: ubuntu-latest
        type: string
      workingBranch:
        default: Testing_workflows
        type: string
      workingRepo:
        default: StateOS_BA
        type: string
      workingOrg:
        default: MertensFlo
        type: string
      callerRepo:
        default: StateOS_BA
        type: string
      callerOrg:
        default: MertensFlo
        type: string
      arm_path:
        default: https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
        type: string
      arm_tar_path:
        default: arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz
        type: string
      arm_dir_path:
        default: ${{github.workspace}}/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi/bin
        type: string
      current_test_element:
        type: string
      flag_arm:
        default: false
        type: boolean
      flag_submodule:
        default: false
        type: boolean
      flag_ninja:
        default: false
        type: boolean
      
jobs:
  example:
    name: test-${{inputs.current_test_element}}
    runs-on: ${{ (inputs.buildSystem)}}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with: 
          repository: ${{inputs.callerOrg}}/${{inputs.callerRepo}}
          submodules: ${{inputs.flag_submodule}}

      - name: Checkout actions repo for wanted branch
        uses: actions/checkout@v4
        with: 
          repository: ${{inputs.workingOrg}}/${{inputs.workingRepo}}
          path: ref_actions_repo
          ref: ${{ inputs.workingBranch }}
          sparse-checkout: |
            .github/actions
          sparse-checkout-cone-mode: false

      - name: build specific commands
        uses: ./.github/actions/universal/action_build_specific_commands
        with:
          arm_path: ${{inputs.arm_path}}
          arm_tar_path: ${{inputs.arm_tar_path}}
          arm_dir_path: ${{inputs.arm_dir_path}}
          flag_arm: ${{inputs.flag_arm}}
  
      - name: check installs
        uses: ./.github/actions/universal/action_check_installs
        with:
          flag_arm: ${{inputs.flag_arm}}

      - name: make example test
        if: ${{inputs.current_test_element == 'example'}}
        uses: ./.github/actions/test/action_example_test

      - name: make static test
        if: ${{inputs.current_test_element == 'static'}}
        uses: ./.github/actions/test/action_static_code_test
        
      - name: make unit test
        if: ${{inputs.current_test_element == 'unit'}}
        uses: ./.github/actions/test/action_unit_test