name: unit test

on:
    workflow_call:
  
jobs:
    unit:
      name: unit test
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Uses checkout submodules
        uses: MertensFlo/StateOS_BA/actions/action_checkout_submodul@Testing_workflows
      - name: install arm-none-eabi-gcc
        uses: ./action_install_arm-none-eabi-gcc
      - name: check arm-none-eabi-gcc version
        uses: ./actions/action_check_installs
      - name: make test
        run: make all -f .unit-test.make